-- ============================================================
-- 007_views_reminders.sql
-- Reminders, plus the derived views the dashboard reads from
-- ============================================================

-- ------------------------------------------------------------
-- REMINDERS
-- source='auto' rows are generated by the system (permit
-- expiring, insurance lapsing); 'manual' is a dispatcher note.
-- ------------------------------------------------------------
create table reminders (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references tenants(id),
  entity_type  text not null,
  entity_id    uuid not null,
  load_id      uuid references loads(id) on delete cascade,
  title        text not null,
  detail       text,
  due_at       timestamptz not null,
  priority     text not null default 'normal'
               check (priority in ('low','normal','high','critical')),
  status       text not null default 'open'
               check (status in ('open','snoozed','done','dismissed')),
  source       text not null default 'manual'
               check (source in ('manual','auto')),
  assigned_to  text,
  completed_at timestamptz,
  created_at   timestamptz not null default now()
);
create index idx_reminders_due  on reminders(tenant_id, status, due_at);
create index idx_reminders_load on reminders(load_id);


-- ------------------------------------------------------------
-- EXPIRING DOCUMENTS
-- One query covers carrier insurance, driver medical cards,
-- CDLs, registrations, and permits — because they're all just
-- documents with an expires_on date.
-- ------------------------------------------------------------
create view v_expiring_documents as
select
  d.tenant_id,
  d.id                         as document_id,
  d.doc_type,
  coalesce(d.title, d.filename) as title,
  d.expires_on,
  (d.expires_on - current_date) as days_remaining,
  dl.entity_type,
  dl.entity_id,
  case
    when d.expires_on < current_date            then 'expired'
    when d.expires_on < current_date + 15       then 'critical'
    when d.expires_on < current_date + 45       then 'warning'
    else 'ok'
  end as severity
from documents d
join document_links dl on dl.document_id = d.id
where d.is_current
  and d.expires_on is not null;


-- ------------------------------------------------------------
-- LOAD PERMIT STATUS
-- Rolls every per-state permit up to one row per load.
-- has_window_conflict is the one that saves money: a permit
-- that's issued but expires before the truck reaches that state.
-- ------------------------------------------------------------
create view v_load_permit_status as
select
  l.id        as load_id,
  l.tenant_id,
  l.load_number,
  count(p.id)                                          as permits_total,
  count(*) filter (where p.status = 'issued')          as permits_issued,
  count(*) filter (where p.status in ('needed','applied','pending'))
                                                       as permits_open,
  count(*) filter (where p.status = 'rejected')        as permits_rejected,
  min(lg.planned_entry_date) filter (
    where p.status in ('needed','applied','pending','rejected')
  )                                                    as first_blocking_date,
  bool_or(p.status = 'issued'
          and p.valid_to is not null
          and lg.planned_entry_date > p.valid_to)      as has_window_conflict
from loads l
left join permits   p  on p.load_id = l.id
left join load_legs lg on lg.id = p.load_leg_id
group by l.id, l.tenant_id, l.load_number;


-- ------------------------------------------------------------
-- LOAD MARGIN
-- Heavy haul margins die on permit and escort surprises, not
-- on linehaul rate. This pulls all three sources together.
-- ------------------------------------------------------------
create view v_load_margin as
select
  l.id        as load_id,
  l.tenant_id,
  l.load_number,
  coalesce(l.linehaul_rate,0) + coalesce(l.fuel_surcharge,0)
    + coalesce(sum(c.amount) filter (where c.kind = 'revenue'), 0)
      as total_revenue,
  coalesce(sum(c.amount) filter (where c.kind = 'cost'), 0)
    + coalesce((select sum(coalesce(p.fee,0) + coalesce(p.service_fee,0))
                  from permits p where p.load_id = l.id), 0)
    + coalesce((select sum(coalesce(e.actual_cost, e.confirmed_rate, e.quoted_rate, 0))
                  from escort_assignments e where e.load_id = l.id), 0)
      as total_cost
from loads l
left join load_charges c on c.load_id = l.id
group by l.id, l.tenant_id, l.load_number, l.linehaul_rate, l.fuel_surcharge;


-- ------------------------------------------------------------
-- DISPATCH CALENDAR
-- Pickups, deliveries, permit validity windows, and escort
-- schedules in one feed the calendar page can read directly.
-- ------------------------------------------------------------
create view v_dispatch_calendar as
select l.tenant_id, 'pickup'::text as kind, l.id as load_id,
       l.load_number as label,
       l.pickup_appt_start as starts_at, l.pickup_appt_end as ends_at
  from loads l where l.pickup_appt_start is not null

union all
select l.tenant_id, 'delivery', l.id, l.load_number,
       l.delivery_appt_start, l.delivery_appt_end
  from loads l where l.delivery_appt_start is not null

union all
select p.tenant_id, 'permit_window', p.load_id,
       p.state || ' permit ' || coalesce(p.permit_number,''),
       p.valid_from::timestamptz, p.valid_to::timestamptz
  from permits p
 where p.status = 'issued' and p.valid_from is not null

union all
select e.tenant_id, 'escort', e.load_id,
       e.role || ' escort', e.scheduled_start, e.scheduled_end
  from escort_assignments e
 where e.scheduled_start is not null;


-- ------------------------------------------------------------
-- LOAD BOARD
-- One row per load with everything a list view needs.
-- (The Fleet Board in 008 is the truck-oriented version.)
-- ------------------------------------------------------------
create view v_load_board as
select
  l.id, l.tenant_id, l.load_number, l.status,
  c.legal_name                        as carrier_name,
  b.name                              as broker_name,
  d.first_name || ' ' || d.last_name  as driver_name,
  fo.city || ', ' || fo.state         as origin,
  fd.city || ', ' || fd.state         as destination,
  l.width_in, l.height_in, l.weight_lb, l.is_superload,
  l.pickup_appt_start, l.delivery_appt_start,
  ps.permits_total, ps.permits_issued, ps.permits_open,
  ps.first_blocking_date, ps.has_window_conflict,
  m.total_revenue - m.total_cost      as margin,
  (select count(*) from escort_assignments e
    where e.load_id = l.id and e.status in ('needed','quoted'))
                                      as escorts_unbooked,
  (select max(occurred_at) from events ev where ev.load_id = l.id)
                                      as last_activity_at
from loads l
left join carriers   c  on c.id  = l.carrier_id
left join brokers    b  on b.id  = l.broker_id
left join drivers    d  on d.id  = l.driver_id
left join facilities fo on fo.id = l.origin_facility_id
left join facilities fd on fd.id = l.dest_facility_id
left join v_load_permit_status ps on ps.load_id = l.id
left join v_load_margin        m  on m.load_id  = l.id;
