-- ============================================================
-- 029_national_golden_lanes.sql
-- Heavy Haul Command
-- Curated National Golden Lane Library
--
-- REFERENCE LANES ONLY.
-- These complement the broad interstate corridors from 027.
-- Live rates, current road conditions, appointments and carrier
-- preferences must still be checked.
--
-- HEAVY HAUL / OVERSIZE:
-- These are market/corridor starting points only.
-- Current permit-authorized routing controls every move.
--
-- Research framework:
-- USDOT/FHWA National Highway Freight Network (NHFN)
-- USDOT/FHWA Freight Analysis Framework (FAF)
-- FHWA major freight corridor / gateway studies
-- ============================================================

alter table public.golden_routes
  add column if not exists lane_type text;

alter table public.golden_routes
  add column if not exists evidence_class text;

alter table public.golden_routes
  add column if not exists confidence_level text;

alter table public.golden_routes
  add column if not exists freight_reason text;

create index if not exists golden_routes_lane_type_idx
  on public.golden_routes (tenant_id, lane_type);

create index if not exists golden_routes_origin_dest_idx
  on public.golden_routes (tenant_id, origin_state, destination_state);

with lane_seed as (
  select *
  from (
    values
    ('North Jersey → Chicago Distribution Lane',
     'dry_van',
     'Newark, NJ',
     'Chicago, IL',
     'NJ',
     'IL',
     array['NJ','PA','OH','IN','IL']::text[],
     array['Allentown, PA','Cleveland, OH']::text[],
     'I-80 / I-90',
     'I-80, I-90',
     'long_haul',
     'major_freight_corridor',
     'high',
     'Major Northeast-to-Midwest distribution and manufacturing lane connecting the New York/New Jersey freight market with Chicago.',
     'FHWA freight-corridor framework; Chicago–New York/New Jersey is a major east-west freight market connection.'),
    ('North Jersey → Atlanta Distribution Lane',
     'dry_van',
     'Newark, NJ',
     'Atlanta, GA',
     'NJ',
     'GA',
     array['NJ','PA','MD','VA','NC','SC','GA']::text[],
     array['Baltimore, MD','Richmond, VA','Charlotte, NC']::text[],
     'Northeast–Southeast I-95 / I-85',
     'I-95, I-85',
     'long_haul',
     'major_freight_corridor',
     'high',
     'Strong population-center and distribution-market connection between the Northeast and Southeast.',
     'NHFN/FAF reference lane connecting major freight-generating metro markets.'),
    ('Los Angeles → Dallas Distribution Lane',
     'dry_van',
     'Los Angeles, CA',
     'Dallas, TX',
     'CA',
     'TX',
     array['CA','AZ','NM','TX']::text[],
     array['Phoenix, AZ','El Paso, TX']::text[],
     'Southwest distribution corridor',
     'I-10, I-20',
     'long_haul',
     'major_freight_corridor',
     'high',
     'Large West Coast import/distribution market linked with a major Texas distribution hub.',
     'NHFN/FAF reference lane linking two high-tonnage freight states and major metro freight markets.'),
    ('Dallas → Atlanta Distribution Lane',
     'dry_van',
     'Dallas, TX',
     'Atlanta, GA',
     'TX',
     'GA',
     array['TX','LA','MS','AL','GA']::text[],
     array['Shreveport, LA','Jackson, MS','Birmingham, AL']::text[],
     'South-Central to Southeast',
     'I-20',
     'regional_long_haul',
     'major_freight_corridor',
     'high',
     'Major distribution and manufacturing markets connected by the I-20 freight corridor.',
     'NHFN/FAF reference lane on a major southern freight corridor.'),
    ('Chicago → Dallas Distribution Lane',
     'dry_van',
     'Chicago, IL',
     'Dallas, TX',
     'IL',
     'TX',
     array['IL','MO','OK','TX']::text[],
     array['St. Louis, MO','Tulsa, OK']::text[],
     'Midwest–Texas distribution corridor',
     'I-55, I-44, I-35',
     'long_haul',
     'major_freight_market_pair',
     'high',
     'Connects two of the nation’s largest inland freight and distribution markets.',
     'FAF/NHFN market-to-market reference lane.'),
    ('Seattle → Portland Distribution Lane',
     'dry_van',
     'Seattle, WA',
     'Portland, OR',
     'WA',
     'OR',
     array['WA','OR']::text[],
     array['Tacoma, WA']::text[],
     'Pacific Northwest I-5',
     'I-5',
     'regional',
     'major_freight_corridor',
     'high',
     'Core Pacific Northwest distribution and port-market lane.',
     'NHFN I-5 freight-corridor reference lane.'),
    ('Central California → Los Angeles Produce Lane',
     'reefer',
     'Fresno, CA',
     'Los Angeles, CA',
     'CA',
     'CA',
     array['CA']::text[],
     array['Bakersfield, CA']::text[],
     'California agricultural-to-consumer lane',
     'CA-99, I-5',
     'regional',
     'commodity_market_lane',
     'high',
     'Central California agricultural production feeding the large Southern California consumer/distribution market.',
     'FAF commodity-flow framework; California is a major agricultural and food freight market.'),
    ('Central California → Dallas Reefer Lane',
     'reefer',
     'Fresno, CA',
     'Dallas, TX',
     'CA',
     'TX',
     array['CA','AZ','NM','TX']::text[],
     array['Bakersfield, CA','Phoenix, AZ','El Paso, TX']::text[],
     'West-to-Texas cold-chain corridor',
     'CA-99, I-10, I-20',
     'long_haul',
     'commodity_market_lane',
     'high',
     'Agricultural origin market feeding a major Texas population and distribution hub.',
     'FAF commodity-flow / major freight-state reference lane.'),
    ('Central California → Chicago Reefer Lane',
     'reefer',
     'Fresno, CA',
     'Chicago, IL',
     'CA',
     'IL',
     array['CA','NV','UT','WY','NE','IA','IL']::text[],
     array['Reno, NV','Salt Lake City, UT','Omaha, NE']::text[],
     'California-to-Midwest cold-chain lane',
     'CA-99, I-80',
     'long_haul',
     'commodity_market_lane',
     'high',
     'California agricultural freight moving toward a major Midwest food-distribution market.',
     'FAF commodity-flow framework using a principal national freight corridor.'),
    ('Central California → North Jersey Reefer Lane',
     'reefer',
     'Fresno, CA',
     'Newark, NJ',
     'CA',
     'NJ',
     array['CA','NV','UT','WY','NE','IA','IL','IN','OH','PA','NJ']::text[],
     array['Salt Lake City, UT','Omaha, NE','Chicago, IL']::text[],
     'California-to-Northeast cold-chain lane',
     'CA-99, I-80',
     'long_haul',
     'commodity_market_lane',
     'high',
     'Agricultural production market connected to the large New York/New Jersey consumer and distribution market.',
     'FAF commodity-flow framework via a major transcontinental freight corridor.'),
    ('South Florida → North Jersey Reefer Lane',
     'reefer',
     'Miami, FL',
     'Newark, NJ',
     'FL',
     'NJ',
     array['FL','GA','SC','NC','VA','MD','DE','NJ']::text[],
     array['Jacksonville, FL','Richmond, VA','Baltimore, MD']::text[],
     'East Coast cold-chain lane',
     'I-95',
     'long_haul',
     'commodity_market_lane',
     'high',
     'Strong food/produce origin market connected with the dense Northeast consumer market.',
     'FAF commodity-flow framework via the I-95 freight backbone.'),
    ('South Texas → Chicago Reefer Lane',
     'reefer',
     'Laredo, TX',
     'Chicago, IL',
     'TX',
     'IL',
     array['TX','OK','MO','IL']::text[],
     array['San Antonio, TX','Dallas, TX','St. Louis, MO']::text[],
     'Border-to-Midwest cold-chain lane',
     'I-35, I-44, I-55',
     'long_haul',
     'gateway_food_lane',
     'high',
     'Major southern border gateway connected to a large Midwest food-distribution market.',
     'FAF gateway and interstate freight-flow reference lane.'),
    ('Birmingham → Atlanta Flatbed Lane',
     'flatbed',
     'Birmingham, AL',
     'Atlanta, GA',
     'AL',
     'GA',
     array['AL','GA']::text[],
     array[]::text[],
     'Southeast steel / construction corridor',
     'I-20',
     'regional',
     'industrial_materials_lane',
     'high',
     'Industrial and steel-producing Birmingham market connected with the large Atlanta construction/distribution market.',
     'Industrial-market fit on an NHFN freight corridor.'),
    ('Houston → Dallas Flatbed Lane',
     'flatbed',
     'Houston, TX',
     'Dallas, TX',
     'TX',
     'TX',
     array['TX']::text[],
     array[]::text[],
     'Texas industrial / construction lane',
     'I-45',
     'regional',
     'industrial_materials_lane',
     'high',
     'Connects Houston industrial/energy freight with the Dallas–Fort Worth construction and distribution market.',
     'Large Texas freight-market pair; industrial and construction fit.'),
    ('Chicago → Detroit Flatbed Lane',
     'flatbed',
     'Chicago, IL',
     'Detroit, MI',
     'IL',
     'MI',
     array['IL','IN','MI']::text[],
     array['Gary, IN']::text[],
     'Great Lakes industrial lane',
     'I-90, I-94',
     'regional',
     'industrial_materials_lane',
     'high',
     'Major Great Lakes manufacturing and metals-market connection.',
     'Major manufacturing corridor on the national freight network.'),
    ('Detroit → Cleveland Flatbed Lane',
     'flatbed',
     'Detroit, MI',
     'Cleveland, OH',
     'MI',
     'OH',
     array['MI','OH']::text[],
     array['Toledo, OH']::text[],
     'Great Lakes manufacturing lane',
     'I-75, I-80',
     'regional',
     'industrial_materials_lane',
     'high',
     'Automotive, metals, machinery and industrial freight connection.',
     'Great Lakes manufacturing-market reference lane.'),
    ('Pittsburgh → North Jersey Flatbed Lane',
     'flatbed',
     'Pittsburgh, PA',
     'Newark, NJ',
     'PA',
     'NJ',
     array['PA','NJ']::text[],
     array['Harrisburg, PA']::text[],
     'Pennsylvania-to-Northeast industrial lane',
     'I-76, I-78',
     'regional_long_haul',
     'industrial_materials_lane',
     'high',
     'Industrial/metals market connected to a major Northeast construction and port/distribution market.',
     'Regional industrial-market reference lane.'),
    ('Charlotte → Atlanta Flatbed Lane',
     'flatbed',
     'Charlotte, NC',
     'Atlanta, GA',
     'NC',
     'GA',
     array['NC','SC','GA']::text[],
     array['Greenville, SC']::text[],
     'Carolinas–Georgia industrial lane',
     'I-85',
     'regional',
     'industrial_materials_lane',
     'high',
     'Construction, manufacturing and building-material freight between fast-growing Southeast markets.',
     'NHFN I-85 regional freight corridor.'),
    ('Houston → Oklahoma City Step Deck Lane',
     'step_deck',
     'Houston, TX',
     'Oklahoma City, OK',
     'TX',
     'OK',
     array['TX','OK']::text[],
     array['Dallas, TX']::text[],
     'Energy / machinery corridor',
     'I-45, I-35',
     'regional_long_haul',
     'machinery_equipment_lane',
     'high',
     'Energy, machinery and industrial-equipment markets with frequent dimensional freight.',
     'Industrial-market fit; verify loaded height and any oversize requirements.'),
    ('Houston → Midland-Odessa Step Deck Lane',
     'step_deck',
     'Houston, TX',
     'Midland, TX',
     'TX',
     'TX',
     array['TX']::text[],
     array['San Antonio, TX']::text[],
     'Texas energy equipment lane',
     'I-10 / West Texas connections',
     'regional_long_haul',
     'energy_equipment_lane',
     'high',
     'Energy-sector machinery and equipment connection between Gulf Coast and Permian Basin markets.',
     'Energy / industrial freight-market reference lane.'),
    ('Detroit → Chicago Step Deck Lane',
     'step_deck',
     'Detroit, MI',
     'Chicago, IL',
     'MI',
     'IL',
     array['MI','IN','IL']::text[],
     array['South Bend, IN']::text[],
     'Great Lakes machinery lane',
     'I-94',
     'regional',
     'machinery_equipment_lane',
     'high',
     'Manufacturing and machinery freight between two major Great Lakes industrial markets.',
     'Great Lakes manufacturing-market reference lane.'),
    ('Cleveland → Chicago Step Deck Lane',
     'step_deck',
     'Cleveland, OH',
     'Chicago, IL',
     'OH',
     'IL',
     array['OH','IN','IL']::text[],
     array['Toledo, OH']::text[],
     'Great Lakes industrial equipment lane',
     'I-80, I-90',
     'regional_long_haul',
     'machinery_equipment_lane',
     'high',
     'Machinery, manufacturing and metal-fabrication freight along a major industrial corridor.',
     'FHWA I-80/I-90 freight-corridor and manufacturing-market fit.'),
    ('North Jersey → Pittsburgh Step Deck Lane',
     'step_deck',
     'Newark, NJ',
     'Pittsburgh, PA',
     'NJ',
     'PA',
     array['NJ','PA']::text[],
     array['Allentown, PA','Harrisburg, PA']::text[],
     'Northeast industrial equipment lane',
     'I-78, I-76',
     'regional_long_haul',
     'machinery_equipment_lane',
     'high',
     'Port/import and Northeast machinery market connected with western Pennsylvania industrial markets.',
     'Northeast port-to-industrial market reference lane.'),
    ('Savannah → Atlanta Step Deck Lane',
     'step_deck',
     'Savannah, GA',
     'Atlanta, GA',
     'GA',
     'GA',
     array['GA']::text[],
     array['Macon, GA']::text[],
     'Port-to-inland equipment lane',
     'I-16, I-75',
     'regional',
     'port_industrial_lane',
     'high',
     'Port cargo, machinery and industrial equipment moving inland to a major Southeast market.',
     'Gateway-to-inland freight-market reference lane.'),
    ('Port Newark → Chicago Specialized Lane',
     'specialized',
     'Port Newark, NJ',
     'Chicago, IL',
     'NJ',
     'IL',
     array['NJ','PA','OH','IN','IL']::text[],
     array['Allentown, PA','Cleveland, OH']::text[],
     'Northeast port-to-Midwest industrial corridor',
     'I-80 / I-90',
     'long_haul',
     'gateway_industrial_lane',
     'high',
     'International gateway connected to a major Midwest manufacturing and distribution market.',
     'FHWA Chicago–New York/New Jersey major freight corridor.'),
    ('Houston → New Orleans Specialized Lane',
     'specialized',
     'Houston, TX',
     'New Orleans, LA',
     'TX',
     'LA',
     array['TX','LA']::text[],
     array['Beaumont, TX','Lake Charles, LA']::text[],
     'Gulf Coast energy / petrochemical corridor',
     'I-10',
     'regional_long_haul',
     'energy_project_cargo_lane',
     'high',
     'Dense Gulf Coast petrochemical, refinery, energy and project-cargo market connection.',
     'Major Gulf Coast industrial corridor on the NHFN.'),
    ('Savannah → Atlanta Specialized Lane',
     'specialized',
     'Savannah, GA',
     'Atlanta, GA',
     'GA',
     'GA',
     array['GA']::text[],
     array['Macon, GA']::text[],
     'Savannah port-to-inland industrial lane',
     'I-16, I-75',
     'regional',
     'gateway_industrial_lane',
     'high',
     'Port and import cargo moving into a major Southeast industrial/distribution market.',
     'Major gateway-to-inland freight connection.'),
    ('Charleston → Charlotte Specialized Lane',
     'specialized',
     'Charleston, SC',
     'Charlotte, NC',
     'SC',
     'NC',
     array['SC','NC']::text[],
     array['Columbia, SC']::text[],
     'Charleston port-to-Carolinas industrial lane',
     'I-26, I-77',
     'regional',
     'gateway_industrial_lane',
     'high',
     'Port cargo connected to the Carolinas manufacturing and distribution market.',
     'Gateway-to-inland freight-market reference lane.'),
    ('Long Beach → Phoenix Specialized Lane',
     'specialized',
     'Long Beach, CA',
     'Phoenix, AZ',
     'CA',
     'AZ',
     array['CA','AZ']::text[],
     array['Blythe, CA']::text[],
     'Southern California port-to-Southwest lane',
     'I-10',
     'regional_long_haul',
     'gateway_industrial_lane',
     'high',
     'Major port gateway connected to the Phoenix industrial and construction market.',
     'Port-to-market lane using an NHFN backbone.'),
    ('Baltimore → Pittsburgh Specialized Lane',
     'specialized',
     'Baltimore, MD',
     'Pittsburgh, PA',
     'MD',
     'PA',
     array['MD','PA']::text[],
     array['Hagerstown, MD']::text[],
     'Mid-Atlantic port-to-industrial lane',
     'I-70, I-76',
     'regional_long_haul',
     'gateway_industrial_lane',
     'high',
     'Port/project cargo connected with western Pennsylvania industrial and machinery markets.',
     'Mid-Atlantic gateway-to-industrial market reference lane.'),
    ('Houston → New Orleans Heavy Haul Market Lane',
     'heavy_haul',
     'Houston, TX',
     'New Orleans, LA',
     'TX',
     'LA',
     array['TX','LA']::text[],
     array['Beaumont, TX','Lake Charles, LA']::text[],
     'Gulf Coast project-cargo market',
     'I-10',
     'regional_long_haul',
     'project_cargo_market',
     'high',
     'Major petrochemical, refinery, energy and project-cargo markets along the Gulf Coast. Use only as a market/corridor starting point.',
     'Industrial/project-cargo market reference; CURRENT OVERSIZE/OVERWEIGHT PERMITS CONTROL ROUTING.'),
    ('Houston → Midland-Odessa Heavy Haul Market Lane',
     'heavy_haul',
     'Houston, TX',
     'Midland, TX',
     'TX',
     'TX',
     array['TX']::text[],
     array['San Antonio, TX']::text[],
     'Texas energy project-cargo market',
     'I-10 / West Texas connections',
     'regional_long_haul',
     'project_cargo_market',
     'high',
     'Energy equipment and project cargo between Gulf Coast suppliers and Permian Basin markets. Permit routing must be independently established.',
     'Energy/project-cargo market reference; CURRENT PERMITS CONTROL ROUTING.'),
    ('Port Newark → Pittsburgh Heavy Haul Market Lane',
     'heavy_haul',
     'Port Newark, NJ',
     'Pittsburgh, PA',
     'NJ',
     'PA',
     array['NJ','PA']::text[],
     array['Harrisburg, PA']::text[],
     'Northeast port-to-industrial market',
     'I-78 / Pennsylvania corridor',
     'regional_long_haul',
     'project_cargo_market',
     'medium',
     'Port/project cargo origin connected to a western Pennsylvania industrial market. Not a pre-approved oversize route.',
     'Port-to-industrial market reference; dimensions, weight, axles and current permits determine the legal route.'),
    ('Baltimore → Pittsburgh Heavy Haul Market Lane',
     'heavy_haul',
     'Baltimore, MD',
     'Pittsburgh, PA',
     'MD',
     'PA',
     array['MD','PA']::text[],
     array['Hagerstown, MD']::text[],
     'Mid-Atlantic port-to-industrial market',
     'I-70 / Pennsylvania corridor',
     'regional_long_haul',
     'project_cargo_market',
     'medium',
     'Port/project cargo and heavy industrial equipment market connection. Route must be permitted for the actual move.',
     'Project-cargo market reference; CURRENT PERMITS CONTROL ROUTING.'),
    ('Savannah → Atlanta Heavy Haul Market Lane',
     'heavy_haul',
     'Savannah, GA',
     'Atlanta, GA',
     'GA',
     'GA',
     array['GA']::text[],
     array['Macon, GA']::text[],
     'Savannah gateway-to-inland project market',
     'I-16 / I-75 corridor',
     'regional',
     'project_cargo_market',
     'medium',
     'Port-origin machinery/project cargo moving toward a major Southeast industrial market. Not a blanket oversize route.',
     'Gateway-to-industrial market reference; current Georgia permits and routing control.'),
    ('Long Beach → Phoenix Heavy Haul Market Lane',
     'heavy_haul',
     'Long Beach, CA',
     'Phoenix, AZ',
     'CA',
     'AZ',
     array['CA','AZ']::text[],
     array['Blythe, CA']::text[],
     'Southern California port-to-Southwest project market',
     'I-10 general corridor',
     'regional_long_haul',
     'project_cargo_market',
     'medium',
     'Port-origin machinery/project freight serving a major Southwest industrial and construction market. Not an oversize-approved route.',
     'Port-to-market reference; California/Arizona permit routing controls.'),
    ('Chicago → Detroit Heavy Haul Market Lane',
     'heavy_haul',
     'Chicago, IL',
     'Detroit, MI',
     'IL',
     'MI',
     array['IL','IN','MI']::text[],
     array['Gary, IN']::text[],
     'Great Lakes heavy industrial market',
     'I-90 / I-94 general corridor',
     'regional',
     'heavy_industrial_market',
     'medium',
     'Large Great Lakes manufacturing and machinery markets. This is a market lane, not a permit-approved oversize route.',
     'Heavy industrial market reference; current state permits and route surveys control.'),
    ('Cleveland → Chicago Heavy Haul Market Lane',
     'heavy_haul',
     'Cleveland, OH',
     'Chicago, IL',
     'OH',
     'IL',
     array['OH','IN','IL']::text[],
     array['Toledo, OH']::text[],
     'Great Lakes heavy industrial market',
     'I-80 / I-90 general corridor',
     'regional_long_haul',
     'heavy_industrial_market',
     'medium',
     'Major steel, machinery and manufacturing markets along a nationally important freight corridor. Not an automatic heavy-haul route.',
     'Industrial-market reference; CURRENT OVERSIZE/OVERWEIGHT PERMITS CONTROL ROUTING.')
  ) as x (
    route_name,
    freight_type,
    origin,
    destination,
    origin_state,
    destination_state,
    states,
    waypoints,
    corridor,
    highways,
    lane_type,
    evidence_class,
    confidence_level,
    freight_reason,
    source_note
  )
),
tenants as (
  select distinct tenant_id
  from public.app_users
  where tenant_id is not null
)
insert into public.golden_routes (
  tenant_id,
  route_name,
  route_class,
  source_note,
  freight_type,
  equipment_type,
  origin,
  destination,
  origin_state,
  destination_state,
  states,
  waypoints,
  corridor,
  highways,
  lane_type,
  evidence_class,
  confidence_level,
  freight_reason,
  general_notes,
  permit_notes,
  clearance_notes,
  travel_restriction_notes,
  successful_uses,
  last_used_on,
  last_verified_on,
  google_maps_url,
  active
)
select
  t.tenant_id,
  l.route_name,
  'reference',
  l.source_note,
  l.freight_type,
  null,
  l.origin,
  l.destination,
  l.origin_state,
  l.destination_state,
  l.states,
  l.waypoints,
  l.corridor,
  l.highways,
  l.lane_type,
  l.evidence_class,
  l.confidence_level,
  l.freight_reason,
  'NATIONAL GOLDEN LANE REFERENCE — ' || l.freight_reason,
  case
    when l.freight_type = 'heavy_haul'
      then 'No permit approval is implied. Obtain and follow current permits for the actual shipment.'
    when l.freight_type in ('step_deck','specialized')
      then 'Verify dimensions and determine whether the current load requires oversize/overweight permits.'
    else null
  end,
  case
    when l.freight_type in ('heavy_haul','step_deck','specialized')
      then 'No clearance guarantee is implied. Verify actual loaded dimensions, structures, bridges, tunnels and restrictions.'
    else null
  end,
  case
    when l.freight_type = 'heavy_haul'
      then 'Verify permitted travel windows, curfews, construction, weather, escort rules, weekend/holiday restrictions and state-specific conditions.'
    else null
  end,
  0,
  null,
  null,
  null,
  true
from tenants t
cross join lane_seed l
where not exists (
  select 1
  from public.golden_routes g
  where g.tenant_id = t.tenant_id
    and g.route_name = l.route_name
    and g.freight_type = l.freight_type
    and g.route_class = 'reference'
);

-- Verification by freight type
select
  freight_type,
  count(*) as national_lane_count
from public.golden_routes
where route_class = 'reference'
  and lane_type is not null
group by freight_type
order by freight_type;

-- New Jersey origin check
select
  freight_type,
  route_name,
  origin,
  destination,
  confidence_level
from public.golden_routes
where route_class = 'reference'
  and origin_state = 'NJ'
order by freight_type, route_name;
